import Head from "next/head";
import About from "./components/About";
import Footer from "./components/Footer";
import Main from "./components/Main";
import Navbar from "./components/NavBar";
import Project from "./components/Project";
import Skill from "./components/Skill";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shop Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <About />
      <Skill />
      <Project />
      <Footer />
    </>
  );
}
